AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'Rakefile'
    - 'config.ru'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'config/environments/*'

Metrics/MethodLength:
  Max: 20
