language: ruby
services:
  - postgresql
rvm:
  - 2.6.3
cache:
  directories:
  - /home/travis/.rvm/
  bundler: true
  yarn: true
before_install:
  - cp config/database.yml.travis config/database.yml
  - bundle install
  - psql -c 'create database laba42_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script:
  - "bundle exec rspec"
  - "bundle exec rubocop"
  - "bundle exec reek"
deploy:
  provider: heroku
  api_key:
    secure: "lv71tdOoap1NtEIM92guaG3gqkPEdk909Z6VJ16sBrnh/6Nes0VSdN78NLjC/UTHELDI9AndI6fA/J3zhELTSuZ4CjZESFzyPMtsw0dAM4g6F55eifKChxtGsGSHgsdODzHRrE7XUmoyIU1SvEGAS+VuANIhPM2IQm6k+sv/xJ4MUs73xsn+EKG4Hsck8JAzvWxozvQs8XI/5pSX6x6tioI4KuOE7UnoecpgCk1Gn/4edhs6/7TqvD93hDyu4S3FF4EdzSuxiYoBCoo9cqS70l0NXtNXh3Ey4OWuad3u6BmoZ6GK3n97HAqr6hoziX0fmAB/nqvqc7kKYMKngXRzDuOOTBVuv7ePvw1EeV6mvBP0IAChdKKGNO1VIqN+6h7W7v3ctOlKagGMsDQCIp9D/UxenKaeA73Er0LeLjjzEd98wagTMbS2+MX+hKXiLFYf4ToozNYxTTAsKpQjctouCer6zoFpEwLyb5z11LGaw4LxVUVR5uSq54Uvt1F1t18aYKf2xmG18iuBFw2URlH0KrUruv0BjPfn3v9OIpE36XUI0hjFRZ0VcjY3pA6MAkkYi1G5EYOKnzNrIvb1TqSaLgKJu9MHbj0/f7aLaySoVdNkPkiOL5PaWeOFRpcVlkJx6P5YrddlSawcVl0MzP0QD4MNTxaEZv0QGrR9nCzVn14="
  app: pure-inlet-49848
  on:
    repo: AnthonyBY/Laba42
